# Generated by Django 3.2.9 on 2022-01-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operationfreedom', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Random',
        ),
    ]
