# Generated by Django 3.2.9 on 2022-01-23 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operationfreedom', '0002_delete_random'),
    ]

    operations = [
        migrations.CreateModel(
            name='Random',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testing', models.CharField(blank=True, max_length=200, null=True)),
                ('question', models.CharField(max_length=255, null=True)),
                ('extra_info', models.CharField(blank=True, max_length=1000, null=True)),
                ('dislike', models.ManyToManyField(blank=True, related_name='dislikee', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, related_name='likee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
