# Generated by Django 3.2.9 on 2022-01-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operationfreedom', '0006_rename_survey_comment_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
