# Generated by Django 3.2.9 on 2022-01-27 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operationfreedom', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
