# Generated by Django 3.2.9 on 2022-01-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationfreedom', '0014_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=750),
        ),
    ]
