# Generated by Django 3.2.9 on 2022-01-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationfreedom', '0015_auto_20220128_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
