# Generated by Django 3.2.9 on 2022-01-30 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operationfreedom', '0016_auto_20220129_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
