# Generated by Django 3.2.9 on 2022-04-05 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operationfreedom', '0019_auto_20220404_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomm',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='randomm',
            name='like',
        ),
        migrations.RemoveField(
            model_name='survey_general',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='survey_general',
            name='like',
        ),
        migrations.DeleteModel(
            name='Random',
        ),
        migrations.DeleteModel(
            name='Randomm',
        ),
        migrations.DeleteModel(
            name='Survey_General',
        ),
    ]
