# Generated by Django 3.2.9 on 2022-03-02 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20220302_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='threadmodel',
            name='created_on',
        ),
    ]
