# Generated by Django 3.2.9 on 2022-03-02 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20220302_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadmodel',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='threadmodel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
