# Generated by Django 3.2.9 on 2022-03-02 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20220302_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='threadmodel',
            name='created_on',
        ),
    ]
