# Generated by Django 3.2.9 on 2022-03-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
