# Generated by Django 3.2.9 on 2022-04-05 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_alter_like_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
