# Generated by Django 3.2.9 on 2022-04-21 16:30

from django.db import migrations, models
import social.validators


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_auto_20220405_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/post_videos', validators=[social.validators.file_size]),
        ),
    ]
