# Generated by Django 3.2.9 on 2022-03-31 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='members.state'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
