# Generated by Django 3.2.9 on 2022-04-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20220401_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(default=False, max_length=70),
        ),
    ]
